appUser/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', include("adminApp.urls")),

    # authentication APIs
    path('signup/', views.signup, name="signup"),
    path('validation-signup/', views.signupFormValid, name="signupValid"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('confirm-password/', views.confirmPassword, name="confirmPassword"),
    path('password-update/', views.updatePassword, name="updatePassword"),

    # personal pages APIs
    path('profile/', views.profilePage, name="profile"),
    path('add-balance/', views.add_balance, name="addBalance"),
    path('check-balance/', views.check_balance, name="checkBalance"),

    # address manage APIs
    path('my-addresses/', views.my_addreses, name="myAddresses"),
    path('set-default-address/', views.set_default_address),
    path('add-new-address/', views.add_address, name="addAddress"),
    path('delete-address/', views.deleteAddress, name="deleteAddress"),

    # orders manage APIs
    path('my-orders/', views.my_orders, name="myOrders"),
    path('view-order-status/<str:orderid>/', views.orderStatus, name="orderStatus"),
    path('cancel-order/', views.cancelOrder, name="cancelOrder"),
    path('return-order/', views.returnOrder, name="returnOrder"),

    # Wishlist APIs
    path('wish-list/', views.wishlistPage, name="wishlistPage"),
    path('add-to-favourite/', views.add_to_favourite, name="addToFavourite"),

    # cart APIs
    path('add-to-cart/', views.addToCart, name="addToCart"),
    path('remove-from-cart/', views.removeFromCart, name="removeFromCart"),
    path('cart/', views.cartPage, name="cartPage"),
    path('add-qantity/', views.add_quantity, name="addQuantity"),
    path('proceed-to-buy/', views.proceedToBuy, name="proceedToBuy"),
    path('choose-payment/', views.choose_payment, name="choosePayment"),
    path('confirm-order/', views.order_confirmed, name="orderConfirm"),

    # search APIs
    path('search-show/', views.searchResponse, name="searchResponse"),
    path('search-history-save/', views.saveSearchHistory, name="saveSearch"),
    path('get-search-history/', views.searchHistory, name="searchHistory"),
    path('search/', views.searchPage, name="searchPage"),

    # Product APIs
    path('category/<str:category>/', views.categoryProduct, name="categoryProduct"),
    path('add-review/', views.add_review, name="addReview"),
    path('add-rating/', views.rateProduct, name="rateProduct"),
    path('view-product/<str:name>/', views.productPage, name="ProductPage"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin-page/', admin.site.urls),
    path('', include("appUser.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root' : settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root' : settings.STATIC_ROOT}),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appUser/models.py
from datetime import date, timedelta
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.template.defaultfilters import slugify

class CustomUserManager(BaseUserManager):

    def _create_user(self, email, password=None, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    phone = models.BigIntegerField(blank=True, null=True)
    wallet = models.FloatField(default=0.0, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()



class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=300, blank=True)
    about = models.TextField(blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    category = models.ManyToManyField(Category, blank=True, related_name="P_category")
    quantity = models.IntegerField(default=0)
    favourites = models.ManyToManyField(CustomUser, blank=True, related_name="user_favourite")
    created_on = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=300, null=True, blank=True)
    image = models.ImageField(upload_to='product/', blank=True, default='product/noimage.jpg')
    avg_rating = models.FloatField(blank=True, default=0.0)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)



class ProductRating(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="rating_prod")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="rating_user")
    rating = models.IntegerField(blank=True)

    def __str__(self):
        return self.user.first_name


class ProductComments(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True) 
    comment = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)


class ProductImage(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_images")
    image = models.ImageField(upload_to='product/', blank=True)

    def __str__(self):
        return self.product.name



class Address(models.Model):
    STATE_CHOICES = [
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Delhi', 'Delhi'),
    ('Goa', 'Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odissa', 'Odissa'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ]
    id = models.AutoField(primary_key=True) 
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=50, blank=True)
    phone = models.BigIntegerField(blank=True)
    pin_code = models.IntegerField(blank=True)
    house = models.CharField(max_length=60, blank=True)
    area = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    default = models.BooleanField(default=False)
    state = models.CharField(max_length=50, choices=STATE_CHOICES, blank=True)

    def __str__(self):
        return(self.house + ", " + self.area + ", " + self.city + ", " + self.state + ", " + str(self.pin_code))


class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=True, default=1)

    def __str__(self):
        return self.user.first_name


class Order(models.Model):
    PAYMENT_CHOICES = [
        ('Wallet', 'Wallet'),
        ('COD', 'COD')
    ]
    STATUS_CHOICES = [
        ('Getting Ready for Packing', 'Getting Ready for Packing'),
        ('Packed', 'Packed'),
        ('Shipped', 'Shipped'),
        ('Out for Delivery', 'Out for Delivery'),
        ('Cancelled', 'Cancelled'),
        ('Delivered', 'Delivered'),
        ('Requested for Return', 'Requested for Return'),
        ('Return Approved', 'Return Approved'),
        ('Returned', 'Returned'),
    ]
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=300, blank=True)
    price = models.FloatField(blank=True, null=True)
    prod_image = models.ImageField(upload_to='product/', blank=True, default='product/noimage.jpg')
    deliver_to = models.CharField(max_length=60, blank=True)
    phone = models.BigIntegerField(blank=True, null=True)
    address = models.CharField(max_length=200, blank=True)
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, blank=True, default='Getting Ready for Packing')
    order_id = models.CharField(max_length=15, blank=True)
    payment_mode = models.CharField(max_length=10, blank=True, choices=PAYMENT_CHOICES)
    amount = models.FloatField(blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    date_time = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    estimate_dd = models.DateField(default=date.today() + timedelta(days=7))

    def __str__(self):
        return self.order_id


    def save(self, *args, **kwargs):  # new
        self.name = self.product.name
        self.price = self.product.price
        self.prod_image = self.product.image
        return super().save(*args, **kwargs)


class SearchHistory(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title

appUser/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.forms import EmailInput, HiddenInput, IntegerField, ModelForm, PasswordInput, TextInput, ImageField


class UserAdminCreationForm(UserCreationForm):
    """
    A Custom form for creating new users.
    """

    class Meta:
        model = CustomUser
        fields = ['email', 'first_name', 'last_name', 'phone', 'password1', 'password2']
        widgets = {
            'email': EmailInput(attrs={'class':'form-control', 'placeholder':'Your email', 'type':'email', 'required':'required'}),
            'first_name': TextInput(attrs={'class':'form-control', 'placeholder':'Your first name', 'type':'text', 'required':'required'}),
            'last_name': TextInput(attrs={'class':'form-control', 'placeholder':'Your last name', 'type':'text', 'required':'required'}),
            'phone': TextInput(attrs={'class':'form-control', 'placeholder':'Your 10-digits number', 'type':'number', 'required':'required'}),
            'password1': TextInput(attrs={'class':'form-control', 'placeholder':'Your password', 'type':'password', 'required':'required'}),
            'password2': TextInput(attrs={'class':'form-control', 'placeholder':'Re-type password', 'type':'password', 'required':'required'}),
        }

templates/appUser/addresses.html
{% extends 'appUser/basic.html' %}
{% load static %}


{% block title %}
<title>My Addresses || Shopaholic.com</title>
{% endblock %}


{% block body %}
<div class="container-fluid p-4">
    <div class="container p-4 border border-dark border-2 rounded rounded-3 shadow w-50">
        <h4 class="pb-3 border-bottom">Your Addresses</h4>
        {% if addresses %}
        {% for a in addresses %}
        <div class="container border p-3 mt-2">
            <h5>{{a.name}}</h5>
            <h6><span>Phone: </span><span class="text-success">{{a.phone}}</span></h6>
            <address>{{a.house}}, {{a.area}}, {{a.city}}, {{a.state}} {{a.pin_code}}</address>
            {% if a.default %}
            <p class="text-primary mb-0 pb-0 d-flex justify-content-between"><span><img
                        src="{% static 'images/default.png' %}" alt="{{a.id}}" class="address"> Choose as
                    Default</span><span><img src="{% static 'images/delete.png' %}" alt="{{a.id}}"
                        class="delete-address"></span></p>
            {% else %}
            <p class="text-primary mb-0 pb-0 d-flex justify-content-between"><span><img
                        src="{% static 'images/not_default.png' %}" alt="{{a.id}}" class="address"> Choose as
                    Default</span><span><img src="{% static 'images/delete.png' %}" alt="{{a.id}}"
                        class="delete-address"></span></p>
            {% endif %}
        </div>
        {% endfor %}
        {% else %}
        <h5 class="text-center">You don't have any saved address</h5>
        {% endif %}

        <button class="btn btn-warning text-white btn-sm w-100 mt-4" data-bs-toggle="modal"
            data-bs-target="#addAddressModal">Add a New Address</button>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="addAddressModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add a Address</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'addAddress' %}" method="post" id="addAddressForm">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="full_name" class="form-label">Full Name</label>
                        <input type="text" name="full_name" id="full_name" required class="form-control">
                    </div>
                    <div class="mb-3">
                        <label for="phone" class="form-label">Phone</label>
                        <input type="number" name="phone" id="phone" required class="form-control">
                    </div>
                    <div class="mb-3">
                        <label for="pincode" class="form-label">Pincode</label>
                        <input type="number" name="pincode" id="pincode" required class="form-control">
                    </div>
                    <div class="mb-3">
                        <label for="house" class="form-label">Flat, House no., Building, Company, Apartment</label>
                        <input type="text" name="house" id="house" required class="form-control">
                    </div>
                    <div class="mb-3">
                        <label for="area" class="form-label">Area, Street, Sector, Village</label>
                        <input type="text" name="area" id="area" required class="form-control">
                    </div>
                    <div class="container">
                        <div class="row px-0">
                            <div class="col-6">
                                <div class="mb-3">
                                    <label for="city" class="form-label">City</label>
                                    <input type="text" name="city" id="city" required class="form-control">
                                </div>
                            </div>
                            <div class="col-6">
                                <label for="state" class="form-label">State</label>
                                <select class="form-select" name="state">
                                    <option hidden disabled selected value> -- select a state -- </option>
                                    <option value="Andhra Pradesh">Andhra Pradesh</option>
                                    <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                                    <option value="Assam">Assam</option>
                                    <option value="Bihar">Bihar</option>
                                    <option value="Chhattisgarh">Chhattisgarh</option>
                                    <option value="Delhi">Delhi</option>
                                    <option value="Goa">Goa</option>
                                    <option value="Gujarat">Gujarat</option>
                                    <option value="Haryana">Haryana</option>
                                    <option value="Himachal Pradesh">Himachal Pradesh</option>
                                    <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                                    <option value="Jharkhand">Jharkhand</option>
                                    <option value="Karnataka">Karnataka</option>
                                    <option value="Kerala">Kerala</option>
                                    <option value="Madhya Pradesh">Madhya Pradesh</option>
                                    <option value="Maharashtra">Maharashtra</option>
                                    <option value="Manipur">Manipur</option>
                                    <option value="Meghalaya">Meghalaya</option>
                                    <option value="Mizoram">Mizoram</option>
                                    <option value="Nagaland">Nagaland</option>
                                    <option value="Odissa">Odissa</option>
                                    <option value="Punjab">Punjab</option>
                                    <option value="Rajasthan">Rajasthan</option>
                                    <option value="Sikkim">Sikkim</option>
                                    <option value="Tamil Nadu">Tamil Nadu</option>
                                    <option value="Telangana">Telangana</option>
                                    <option value="Tripura">Tripura</option>
                                    <option value="Uttar Pradesh">Uttar Pradesh</option>
                                    <option value="Uttarakhand">Uttarakhand</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button type="button" class="btn btn-secondary btn-sm px-2 me-3"
                            data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary px-2 btn-sm me-3">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    var CSRF_TOKEN = '{{ csrf_token }}';
</script>
<script src="{% static 'js/addresses.js' %}"></script>
{% endblock %}

templates/appUser/categoryProduct.html
{% extends 'appUser/basic.html' %}
{% load static %}

{% block title %}
<title>{{category}} || Product by Category</title>
{% endblock %}

{% block body %}
<div class="container-fluid d-flex justify-content-center p-4">
    <div class="container border p-3 w-75">
        <h4 class="fw-bold">{{category}} <span class="text-secondary">(Top Rated)</span></h4>
        <div class="container p-0" id="wishlist-box">
            {% if prod %}
            {% for p in prod %}
            <div class="container bg-white cart-box-1 border mt-3 p-3" id="fav-item{{p.id}}">
                <div class="row">
                    <div class="col-md-2">
                        <div class="conatiner d-flex justify-content-center">
                            <img src="{{p.image.url}}" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-md-10">
                        <div class="container p-2">
                            <h4><a href="/view-product/{{p.slug}}/"
                                    class="text-dark text-decoration-none">{{p.name}}</a></h4>
                            <h6 class="text-danger">Price: ₹{{p.price}}</h6>
                            <p>Rating: <span class="text-success">{{p.avg_rating}}/5</span></p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h2 class="p-4 text-center mb-0 text-danger">No Product in this Category</h2>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/appUser/home.html
{% extends 'appUser/basic.html' %}
{% load static %}

{% block title %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<title>Home || Shopaholic</title>
{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="container-fluid">
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'images/home.jpg' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/sale.png' %}" class="d-block w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>

    <div class="container mt-5 border shadow-sm p-3">
        <div class="d-flex justify-content-between">
            <h4 class="border-bottom pb-3 fw-bold">Smartphones in ELECTRONICS</h4>
            <a href="/category/Smartphones/">More Items <span class="fw-bold">&#8594;</span></a>
        </div>
        <div>
            <div class="box-1">
                {% for p in prod %}
                <a class="box-2 border text-decoration-none p-3 mx-2" href="/view-product/{{p.slug}}/">
                    <div class="box-3 container d-flex justify-content-center">
                        <img src="{{p.image.url}}" alt="" class="img-fluid">
                    </div>
                    <h6 class="border-top pt-2 text-danger">Rs. {{p.price}}</h6>
                    <p class="text-1 text-dark">{{p.name|truncatechars:100}}</p>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>


    <div class="container mt-5 border shadow-sm p-3">
        <div class="d-flex justify-content-between">
            <h4 class="border-bottom pb-3 fw-bold">Shirt in MEN FASHION</h4>
            <a href="/category/Men-Shirts/">More Items <span class="fw-bold">&#8594;</span></a>
        </div>
        <div>
            <div class="box-1">
                {% for p in prod_ms %}
                <a class="box-2 border text-decoration-none p-3 mx-2" href="/view-product/{{p.slug}}/">
                    <div class="box-3 container d-flex justify-content-center">
                        <img src="{{p.image.url}}" alt="" class="img-fluid">
                    </div>
                    <h6 class="border-top pt-2 text-danger">Rs. {{p.price}}</h6>
                    <p class="text-1 text-dark">{{p.name|truncatechars:100}}</p>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>

</div>


{% endblock %}

templates/appUser/login.html
{% extends 'appUser/basic.html' %}
{% load static %}

{% block title %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
<title>Login || Shopaholic.com</title>
{% endblock %}


{% block body %}
<div class="container-fluid d-flex justify-content-center align-items-center main-1">
    <div class="container border border-dark border-3 p-4 w-50 shadow bg-white">
        <h1 class="text-center text-dark fw-bold mb-4">Shopaholic</h1>
        <div class="text-center">
            <h4 class="text-dark fw-bold text-center pb-2 rounded">LOGIN</h4>
        </div>
        <form action="{% url 'login' %}" method="post" class="pt-4 border-top border-1">
            {% csrf_token %}
            <div class="mb-3">
                <label for="email" class="fw-bold mb-1 ps-1">Email*</label>
                <input type="email" name="email" id="email" placeholder="Your email" required class="form-control">
            </div>
            <div class="mb-3">
                <label for="password" class="fw-bold mb-1 ps-1">Password*</label>
                <input type="password" name="password" id="password" placeholder="Your password" required class="form-control">
            </div>
            {% if messages %}
            <ul class="messages ps-0">
                {% for message in messages %}
                {% if message.tags == 'error' %}
                <p class="text-danger text-center d-block my-0 pb-0">{{ message }}</p>
                {% elif message.tags == 'success' %}
                <p class="text-primary text-center d-block my-0 pb-0">{{ message }}</p>
                {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-outline-dark fw-bold w-50">Login</button>
            </div>
        </form>
    </div>
</div>




{% endblock %}

templates/appUser/rough.html
<body>
    <h1>Harsh</h1>
    <h2>Gupta</h2>
    <h3>055</h3>
    <h4>1812231055</h4>
    <h5>1812231040</h5>
    <h5>1812231040</h5>
    <h2>11111111111111111111111111111111111</h2>
    <h1>2763674435656</h1>

    <h3>222222222222222</h3>
    <h1>3333333333333333</h1>
    <h4>222222222222222</h4>
    <address>123323</address>
</body>

templates/appUser/rough2.html
<body>
    <h1>Rough2</h1>
</body>

templates/appUser/signup.html
{% extends 'appUser/basic.html' %}
{% load static %}

{% block title %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
<title>Signup || Shopaholic.com</title>
{% endblock %}


{% block body %}
<div class="container-fluid d-flex justify-content-center align-items-center main-1">
    <div class="container border border-dark border-3 p-4 w-75 shadow bg-white">
        <h1 class="text-center text-dark fw-bold mb-4">Shopaholic</h1>
        <div class="text-center">
            <h4 class="text-dark fw-bold text-center pb-2 rounded">SIGNUP</h4>
        </div>
        <form action="" method="post" class="pt-4 border-top border-1" id="signupform">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="first_name" class="fw-bold mb-1 ps-1">First Name*</label>
                        {{form.first_name}}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="last_name" class="fw-bold mb-1 ps-1">Last Name*</label>
                        {{form.last_name}}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="id_email" class="fw-bold mb-1 ps-1">Email*</label>
                        {{form.email}}
                        <span class="invalid-feedback" id="msg-email"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="id_phone" class="fw-bold mb-1 ps-1">Phone*</label>
                        {{form.phone}}
                        <span class="invalid-feedback" id="msg-phone"></span>
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="id_password1" class="fw-bold mb-1 ps-1">Password*</label>
                {{form.password1}}
                <span class="invalid-feedback" id="msg-password1"></span>
            </div>
            <div class="mb-3">
                <label for="id_password2" class="fw-bold mb-1 ps-1">Confirm Password*</label>
                {{form.password2}}
                <span class="invalid-feedback" id="msg-password2"></span>
            </div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                {% if message.tags == 'error' %}
                <p class="text-danger text-center d-block my-0 pb-0">{{ message }}</p>
                {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-outline-dark fw-bold w-50">Register</button>
            </div>
        </form>
    </div>
</div>




<script src="{% static 'js/signup.js' %}"></script>


{% endblock %}